version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql.Dockerfile
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: yourpassword
    networks:
      - my-network
    ports:
      - "3306:3306"

  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis.Dockerfile
    networks:
      - my-network
    ports:
      - "6379:6379"

networks:
  my-network:
    driver: bridge